# Generated by Django 4.1.6 on 2024-05-07 19:11

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff_module', '0001_initial'),
        ('student_module', '0001_initial'),
        ('teacher_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('is_response', models.BooleanField(default=False, verbose_name='پاسخ داده شده؟')),
                ('from_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_module.staff', verbose_name='اپراتور')),
                ('from_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_module.student', verbose_name='دانشجو')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600, verbose_name='عنوان سوالات')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('priority', models.IntegerField(unique=True, verbose_name='ترتیب')),
                ('for_group', multiselectfield.db.fields.MultiSelectField(choices=[('student', 'دانشجو'), ('teacher', 'استاد'), ('staff', 'کارمند')], max_length=100, verbose_name='برای گروه...')),
            ],
            options={
                'verbose_name': 'سوال کاربر',
                'verbose_name_plural': 'سوالات کاربر',
            },
        ),
        migrations.CreateModel(
            name='IndexMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=700, verbose_name='عنوان پیام')),
                ('content', models.TextField(verbose_name='محتوای پیام')),
                ('priority', models.IntegerField(unique=True, verbose_name='اولویت')),
                ('for_group', multiselectfield.db.fields.MultiSelectField(choices=[('student', 'دانشجو'), ('teacher', 'استاد'), ('staff', 'کارمند')], max_length=100, verbose_name='برای گروه...')),
            ],
            options={
                'verbose_name': 'اطلاعیه',
                'verbose_name_plural': 'اطلاعیه ها',
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(verbose_name='')),
                ('is_closed', models.BooleanField(default=False, verbose_name='')),
                ('contact_message', models.ManyToManyField(to='site_module.contactmessages', verbose_name='')),
                ('from_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_module.staff', verbose_name='برای کارمند')),
                ('from_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_module.student', verbose_name='برای دانشجو')),
                ('from_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher_module.teacher', verbose_name='برای استاد')),
            ],
        ),
    ]
