# Generated by Django 4.1.6 on 2024-05-28 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0004_alter_student_last_updated_date'),
        ('staff_module', '0001_initial'),
        ('site_module', '0002_alter_indexmessages_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessages',
            name='from_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_module.staff', verbose_name='اپراتور'),
        ),
        migrations.AlterField(
            model_name='contactmessages',
            name='from_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_module.student', verbose_name='دانشجو'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='contact_message',
            field=models.ManyToManyField(blank=True, to='site_module.contactmessages', verbose_name='پیام ها'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='بسته شده / بسته نشده'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='subject',
            field=models.TextField(verbose_name='موضوع'),
        ),
    ]
