# Generated by Django 4.1.6 on 2024-05-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_alter_contactmessages_from_operator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessages',
            options={'verbose_name': 'پیام های تیکت', 'verbose_name_plural': 'پیام های تیکت ها'},
        ),
        migrations.AlterModelOptions(
            name='contactrequest',
            options={'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت ها'},
        ),
        migrations.AddField(
            model_name='contactmessages',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان ارسال'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان ارسال'),
        ),
    ]
