# Generated by Django 4.1.6 on 2024-05-07 19:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField(verbose_name='مبلغ')),
                ('type', models.CharField(choices=[('insurance', 'بیمه'), ('dormitory_tuition', 'شهریه خوابگاه'), ('fixed_tuition', 'شهریه ثابت'), ('variable_tuition', 'شهریه متغیر'), ('student_welfare_fund_facilities', 'تسهیلات صندوق رفاه دانشجویی')], db_column='type_en', max_length=300, verbose_name='نوع صورت حساب')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور')),
                ('bill_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='شناسه صورت حساب')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده/نشده')),
            ],
            options={
                'verbose_name': 'صورت حساب',
                'verbose_name_plural': 'صورت حساب ها',
            },
        ),
        migrations.CreateModel(
            name='EducationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام گروه آموزشی')),
            ],
            options={
                'verbose_name': 'گروه آموزشی',
                'verbose_name_plural': 'گروه های آموزشی',
            },
        ),
        migrations.CreateModel(
            name='ExamTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان نمایشی')),
                ('start_time', models.DateTimeField(verbose_name='زمان شروع آزمون')),
                ('end_time', models.DateTimeField(verbose_name='زمان پایان آزمون')),
            ],
            options={
                'verbose_name': 'زمانبندی آزمون',
                'verbose_name_plural': 'زمانبندی آزمون ها',
            },
        ),
        migrations.CreateModel(
            name='FixedTuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('continuous_associate', 'کاردانی پیوسته'), ('discontinuous_associate', 'کاردانی نا پیوسته'), ('bachelors_degree', 'کارشناسی پیوسته'), ('discontinuous_bachelors_degree', 'کارشناسی نا پیوسته'), ('masters', 'کارشناسی ارشد'), ('doctorate', 'دکترا')], db_column='section_en', max_length=300, verbose_name='مقطع رشته')),
                ('cost', models.SmallIntegerField(verbose_name='هزینه شهریه ثابت')),
            ],
            options={
                'verbose_name': 'شهریه ثابت',
                'verbose_name_plural': 'شهریه های ثابت',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=300, verbose_name='نام درس')),
                ('lesson_code', models.SmallIntegerField(verbose_name='کد درس')),
                ('lesson_course', models.CharField(choices=[('foundation', 'پایه'), ('professional', 'تخصصی'), ('main', 'اصلی'), ('general', 'عمومی')], db_column='lesson_course_type_en', max_length=200, null=True, verbose_name='نوع درس')),
                ('theoretical_unit', models.CharField(blank=True, choices=[('half_units', 'نیم واحد'), ('single_units', 'یک واحد'), ('two_units', 'دو واحد'), ('three_units', 'سه واحد'), ('four_units', 'چهار واحد'), ('five_units', 'پنج واحد')], db_column='theoretical_unit_en', max_length=200, null=True, verbose_name='واحد نظری')),
                ('practical_units', models.CharField(blank=True, choices=[('half_units', 'نیم واحد'), ('single_units', 'یک واحد'), ('two_units', 'دو واحد'), ('three_units', 'سه واحد'), ('four_units', 'چهار واحد'), ('five_units', 'پنج واحد')], db_column='practical_units_en', max_length=200, null=True, verbose_name='واحد عملی')),
                ('lesson_type', models.CharField(choices=[('practical', 'عملی'), ('theoretical', 'نظری'), ('practical_theoretical', 'نظری - عملی')], db_column='lesson_type_en', max_length=200, verbose_name='نوع درس رشته')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'درس ها',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=300, verbose_name='نام رشته')),
                ('section', models.CharField(choices=[('continuous_associate', 'کاردانی پیوسته'), ('discontinuous_associate', 'کاردانی نا پیوسته'), ('bachelors_degree', 'کارشناسی پیوسته'), ('discontinuous_bachelors_degree', 'کارشناسی نا پیوسته'), ('masters', 'کارشناسی ارشد'), ('doctorate', 'دکترا')], db_column='section_en', max_length=300, verbose_name='مقطع رشته')),
            ],
            options={
                'verbose_name': 'رشته تحصیلی',
                'verbose_name_plural': 'رشته های تحصیلی',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField(verbose_name='مبلغ پرداخت شده')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پرداخت')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='شناسه پرداخت')),
                ('status', models.CharField(choices=[('confirmed', 'تایید شده'), ('pending', 'در حال بررسی'), ('rejected', 'رد شده')], db_column='status_en', max_length=300, null=True, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت ها',
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='ظرفیت')),
                ('class_formation_time', models.CharField(blank=True, choices=[('mon_8_10', 'دوشنبه از 8 تا 10'), ('mon_10_12', 'دوشنبه از 10 تا 12'), ('mon_13_15', 'دوشنبه از 13 تا 15'), ('mon_15_17', 'دوشنبه از 15 تا 17'), ('mon_8_11', 'دوشنبه از 8 تا 11'), ('mon_11_12d30_and_13_14d30', 'دوشنبه از 11 تا 12:30 و 13 تا 14:30'), ('mon_15_18', 'دوشنبه از 15 تا 18'), ('mon_18_21', 'دوشنبه از 18 تا 21'), ('tue_8_10', 'سه\u200cشنبه از 8 تا 10'), ('tue_10_12', 'سه\u200cشنبه از 10 تا 12'), ('tue_13_15', 'سه\u200cشنبه از 13 تا 15'), ('tue_15_17', 'سه\u200cشنبه از 15 تا 17'), ('tue_8_11', 'سه\u200cشنبه از 8 تا 11'), ('tue_11_12d30_and_13_14d30', 'سه\u200cشنبه از 11 تا 12:30 و 13 تا 14:30'), ('tue_15_18', 'سه\u200cشنبه از 15 تا 18'), ('tue_18_21', 'سه\u200cشنبه از 18 تا 21'), ('wed_8_10', 'چهارشنبه از 8 تا 10'), ('wed_10_12', 'چهارشنبه از 10 تا 12'), ('wed_13_15', 'چهارشنبه از 13 تا 15'), ('wed_15_17', 'چهارشنبه از 15 تا 17'), ('wed_8_11', 'چهارشنبه از 8 تا 11'), ('wed_11_12d30_and_13_14d30', 'چهارشنبه از 11 تا 12:30 و 13 تا 14:30'), ('wed_15_18', 'چهارشنبه از 15 تا 18'), ('wed_18_21', 'چهارشنبه از 18 تا 21'), ('thu_8_10', 'پنج\u200cشنبه از 8 تا 10'), ('thu_10_12', 'پنج\u200cشنبه از 10 تا 12'), ('thu_13_15', 'پنج\u200cشنبه از 13 تا 15'), ('thu_15_17', 'پنج\u200cشنبه از 15 تا 17'), ('thu_8_11', 'پنج\u200cشنبه از 8 تا 11'), ('thu_11_12d30_and_13_14d30', 'پنج\u200cشنبه از 11 تا 12:30 و 13 تا 14:30'), ('thu_15_18', 'پنج\u200cشنبه از 15 تا 18'), ('thu_18_21', 'پنج\u200cشنبه از 18 تا 21'), ('fri_8_10', 'جمعه از 8 تا 10'), ('fri_10_12', 'جمعه از 10 تا 12'), ('fri_13_15', 'جمعه از 13 تا 15'), ('fri_15_17', 'جمعه از 15 تا 17'), ('fri_8_11', 'جمعه از 8 تا 11'), ('fri_11_12d30_and_13_14d30', 'جمعه از 11 تا 12:30 و 13 تا 14:30'), ('fri_15_18', 'جمعه از 15 تا 18'), ('fri_18_21', 'جمعه از 18 تا 21')], db_column='class_formation_time_en', max_length=200, null=True, verbose_name='زمان تشکیل کلاس')),
            ],
            options={
                'verbose_name': 'درس ارائه شده',
                'verbose_name_plural': 'دروس ارائه شده',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.IntegerField(null=True, unique=True, verbose_name='شماره ترم')),
                ('is_main_semester', models.BooleanField(default=False, null=True, verbose_name='نیمسال جاری؟')),
                ('select_unit_permission', models.BooleanField(default=False, verbose_name='مجوز انتخاب واحد')),
                ('start_select_unit_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع انتخاب واحد')),
                ('end_select_unit_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان انتخاب واحد')),
            ],
            options={
                'verbose_name': 'ترم',
                'verbose_name_plural': 'ترم ها',
            },
        ),
        migrations.CreateModel(
            name='VariableTuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('continuous_associate', 'کاردانی پیوسته'), ('discontinuous_associate', 'کاردانی نا پیوسته'), ('bachelors_degree', 'کارشناسی پیوسته'), ('discontinuous_bachelors_degree', 'کارشناسی نا پیوسته'), ('masters', 'کارشناسی ارشد'), ('doctorate', 'دکترا')], db_column='section_en', max_length=300, verbose_name='مقطع رشته')),
                ('one_theoretical_unit', models.SmallIntegerField(verbose_name='میزان شهریه برای یک واحد نظری')),
                ('one_practical_unit', models.SmallIntegerField(verbose_name='میزان شهریه برای یک واحد عملی')),
                ('educational_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_module.educationgroup', verbose_name='گروه آموزشی')),
                ('for_semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service_module.semester', verbose_name='برای نیمسال')),
            ],
            options={
                'verbose_name': 'شهریه متغیر',
                'verbose_name_plural': 'شهریه های متغیر',
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='شماره درخواست')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('request_type', models.CharField(choices=[('permission_select_unit', 'مجوز انتخاب واحد'), ('request_for_facilities', 'درخواست تسهیلات')], db_column='request_type_en', max_length=300, verbose_name='نوع درخواست')),
                ('status', models.CharField(choices=[('confirmed', 'تایید شده'), ('rejected', 'رد شده'), ('pending', 'در حال بررسی')], db_column='status_en', max_length=300, null=True, verbose_name='وضعیت')),
                ('request_text', models.TextField(blank=True, null=True, verbose_name='متن درخواست')),
                ('for_semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service_module.semester', verbose_name='نیمسال موثر')),
            ],
            options={
                'verbose_name': 'درخواست',
                'verbose_name_plural': 'درخواست ها',
            },
        ),
    ]
