# Generated by Django 4.1.6 on 2024-05-07 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_module', '0001_initial'),
        ('student_module', '0001_initial'),
        ('teacher_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='for_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_module.student', verbose_name='برای دانشجو'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='exam_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_module.examtime', verbose_name='زمان امتحان'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='for_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_module.semester', verbose_name='ترم ارائه شده'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_module.lesson', verbose_name='نام درس'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='student',
            field=models.ManyToManyField(blank=True, to='student_module.student', verbose_name='دانشجویان'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_module.teacher', verbose_name='نام استاد'),
        ),
        migrations.AddField(
            model_name='payment',
            name='for_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_module.bill', verbose_name='برای صورت حساب'),
        ),
        migrations.AddField(
            model_name='payment',
            name='for_semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service_module.semester', verbose_name='برای نیمسال'),
        ),
        migrations.AddField(
            model_name='payment',
            name='for_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_module.student', verbose_name='دانشجو'),
        ),
        migrations.AddField(
            model_name='major',
            name='educational_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_module.educationgroup', verbose_name='گروه آموزشی'),
        ),
        migrations.AddField(
            model_name='fixedtuition',
            name='educational_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_module.educationgroup', verbose_name='گروه آموزشی'),
        ),
        migrations.AddField(
            model_name='fixedtuition',
            name='entrance_semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service_module.semester', verbose_name='برای ورودی نیمسال'),
        ),
        migrations.AddField(
            model_name='bill',
            name='for_semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service_module.semester', verbose_name='نیمسال موثر'),
        ),
        migrations.AddField(
            model_name='bill',
            name='for_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_module.student', verbose_name='دانشجو'),
        ),
    ]
