# Generated by Django 4.1.6 on 2024-05-07 19:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='نمره')),
                ('for_semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service_module.semester', verbose_name='برای نیمسال')),
            ],
            options={
                'verbose_name': 'نمره',
                'verbose_name_plural': 'نمرات',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('student_number', models.CharField(max_length=200, unique=True, verbose_name='شماره دانشجویی')),
                ('education_status', models.CharField(choices=[('studying', 'در حال تحصیل'), ('graduated', 'فارغ التحصیل')], db_column='education_status_en', max_length=200, verbose_name='وضعیت تحصیلی')),
                ('gpa', models.FloatField(verbose_name='معدل دانشجو')),
                ('units_obtained', models.FloatField(verbose_name='تعداد واحد های اخذ شده')),
                ('units_passed', models.FloatField(verbose_name='تعداد واحد های گذرانده شده')),
                ('units_rejected', models.FloatField(verbose_name='تعداد واحد های رد شده')),
                ('semester_passed', models.IntegerField(verbose_name='سنوات (ترم) گذرانده')),
                ('semesters_conditional', models.IntegerField(verbose_name='تعداد نیم سال های مشروطی')),
                ('start_date_of_study', models.DateField(verbose_name='تاریخ شروع تحصیل')),
                ('deadline_date_of_study', models.DateField(verbose_name='تاریخ آخرین مهلت پایان تحصیل')),
                ('last_updated_date', models.DateField(verbose_name='تاریخ بروزرسانی')),
                ('admission', models.CharField(choices=[('by_test', 'با آزمون'), ('no_test', 'بدون آزمون')], db_column='admission_en', max_length=200, null=True, verbose_name='نوع پذیرش')),
                ('financial_balance', models.SmallIntegerField(default=0, null=True, verbose_name='تراز مالی')),
                ('amount_payable', models.SmallIntegerField(default=0, null=True, verbose_name='قابل پرداخت')),
                ('amount_paid', models.SmallIntegerField(default=0, null=True, verbose_name='پرداخت شده')),
                ('admission_semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service_module.semester', verbose_name='نیم سال پذیرش')),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service_module.major', verbose_name='رشته تحصیلی')),
                ('registered_semesters', models.ManyToManyField(blank=True, related_name='registered_semesters_set', to='service_module.semester', verbose_name='نیم سال های ثبت شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دانشجو',
                'verbose_name_plural': 'دانشجویان',
            },
        ),
        migrations.CreateModel(
            name='StudentGradeAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appel_text', models.TextField(verbose_name='متن اعتراض')),
                ('response_teacher', models.TextField(verbose_name='پاسخ استاد')),
                ('is_response', models.BooleanField(default=False, verbose_name='پاسخ داده شده / نشده')),
                ('for_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_module.student', verbose_name='دانشجو')),
                ('mark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_module.marks', verbose_name='نمره مرتبط')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service_module.semester', verbose_name='نیمسال')),
            ],
            options={
                'verbose_name': 'اعتراض به نمره',
                'verbose_name_plural': 'اعتراض به نمرات',
            },
        ),
        migrations.CreateModel(
            name='SemesterGPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_GPA', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='معدل نیمسال')),
                ('total_GPA', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='معدل تاکنون')),
                ('obtained_units', models.FloatField(verbose_name='واحد های اخذ شده نیمسال')),
                ('passed_units', models.FloatField(verbose_name='واحد های گذرانده نیمسال')),
                ('rejected_units', models.FloatField(verbose_name='واحد های رد شده نیمسال')),
                ('for_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_module.student', verbose_name='دانشجو')),
                ('mark', models.ManyToManyField(blank=True, to='student_module.marks', verbose_name='دروس نیمسال')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service_module.semester', verbose_name='نیمسال')),
            ],
            options={
                'verbose_name': 'معدل',
                'verbose_name_plural': 'معدل ها',
            },
        ),
        migrations.AddField(
            model_name='marks',
            name='for_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_module.student', verbose_name='دانشجو'),
        ),
        migrations.AddField(
            model_name='marks',
            name='presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_module.presentation', verbose_name='درس ارائه شده'),
        ),
        migrations.CreateModel(
            name='EvaluationByStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_skills', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='مهارت تدریس')),
                ('punctuality', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='وقت شناسی')),
                ('respectful_behavior', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='رفتار محترمانه')),
                ('for_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_module.student', verbose_name='دانشجو')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_module.presentation', verbose_name='ارائه مرتبط')),
            ],
            options={
                'verbose_name': 'ارزیابی استاد',
                'verbose_name_plural': 'ارزیابی اساتید',
            },
        ),
    ]
