# Generated by Django 4.1.6 on 2024-05-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.FloatField(default=0, verbose_name='معدل دانشجو'),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester_passed',
            field=models.IntegerField(default=0, verbose_name='سنوات (ترم) گذرانده'),
        ),
        migrations.AlterField(
            model_name='student',
            name='semesters_conditional',
            field=models.IntegerField(default=0, verbose_name='تعداد نیم سال های مشروطی'),
        ),
        migrations.AlterField(
            model_name='student',
            name='units_obtained',
            field=models.FloatField(default=0, verbose_name='تعداد واحد های اخذ شده'),
        ),
        migrations.AlterField(
            model_name='student',
            name='units_passed',
            field=models.FloatField(default=0, verbose_name='تعداد واحد های گذرانده شده'),
        ),
        migrations.AlterField(
            model_name='student',
            name='units_rejected',
            field=models.FloatField(default=0, verbose_name='تعداد واحد های رد شده'),
        ),
    ]
