# Generated by Django 4.1.6 on 2024-05-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0002_alter_student_gpa_alter_student_semester_passed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='deadline_date_of_study',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ آخرین مهلت پایان تحصیل'),
        ),
    ]
